Shaping codeanalyzer to work with DGI c2g
konveyor/dgi-code-analyzer pull request #5
Opened 2023-05-24 16:17 UTC by rahlk

List of changes:

- Rename project name and cli: `code2graph` --to--> `codeanalyzer`
- Remove demos and other jars from the project. These will be hosted elsewhere. 
- Codeanalyzer now produces a single JSON consisting of a (context insensitive) SDG graph.

2023-05-25 12:27 UTC, rofrano approved these changes
Looks good to me.

2023-05-25 12:43 UTC, rofrano requested changes
Please add IBM Copyright to all of the Java files.

Also if I'm reading this diff correctly, it looks like you may have renamed files outside of `git`. This makes git think they were deleted and looses all git history for that file. In the future use:

```bash
git mv oldFilename.java newFilename.java
```

So that git knows it was renamed and not deleted and recreated. This preserves the file history.

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/GraphAugmentor.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/NodeFinder.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/WalaSPTGraph.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/utils/Graph2JSON.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/utils/graph/AbstractGraphEdge.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano commented on src/main/java/org/konveyor/dgi/utils/graph/AbstractGraphNode.java
Please add IBM Copyright to this Java file

2023-05-25 12:43 UTC, rofrano requested changes
Please add IBM Copyright to all of the Java files.

Also if I'm reading this diff correctly, it looks like you may have renamed files outside of `git`. This makes git think they were deleted and looses all git history for that file. In the future use:

```bash
git mv oldFilename.java newFilename.java
```

So that git knows it was renamed and not deleted and recreated. This preserves the file history.

2023-06-01 03:08 UTC, rahlk commented
@rofrano 
- I have added license information to all the files that I created.
- I have dockerized the application. Once we create a container in quay.io, we may host it there.

2023-06-01 12:07 UTC, rofrano approved these changes
Looks great!

2023-06-01 12:07 UTC, merged